### ISSUE TITLE
need a genre / style

### ISSUE THREAD

**Issue by vlraymond** [vlraymond/bootcamp2017#9]
please give me a genre or a style for the story

**Comment by Ianjon** [comment]
There once was a land, far far away over the mountains, over the waterfalls that rivaled the Niagara falls, but had a more amazonian look. There was a little root that sprouted up from the ground. Day by day it would slowly grow. Then one day, the root just popped out of the ground, resembling an action figure in height, but made out of very flexible twigs and sticks. A walking tiny root person. Taking his first steps outside of the ground, he realized that he loves bathing in the sun, so that's what he would do for the next few months. Without realizing it, he spent the next half year with his legs rooted into the ground while basking in the nights of sunlight and during the night, the starry night sky that houses a full moon every two weeks. Within that half year, he grew to the size of a fit 8th grade child. Not knowing that he grew so much, it was easier to maneuver and cross distances. One day, he was halted in his joy of exploring by a large river bed. Not knowing what it was scared him a little, but as he approached closer and closer, his feet were telling him that it was the water that he'd absorbed every since he came to be. Directly drinking from the water, he realized it was missing a few things that the ground provided. He didn't mind it, honestly he was ecstatic because it was something very new to himself.  After playing around with his new found information, he still pondered on how he would cross the large river bed. He tried crossing it Jason style, just walk right through it. It he didn't work since he's made of living wood, he would float. By the new found anger of not knowing how to cross this river bed, he started swinging his arms in a tantrum like most 2 year olds would. As he was swinging his arms in frustration, he was able to expand his arms and legs, detach them at the length and grow other plants. After his tantrum was over, he was surrounded by a bed of flowers, tiny sprouted trees, and bushes. To the new area surroundings, he was very surprised, but not as surprised when he looked at his legs. He was a staggering 13ft tall with orangutan arms as far as fairbanks trees, but no where near as thick. Shocked by his discovery, he tried to forcibly extend his arms to the other side. He was able to extend his arms about 3/4's of the way, to which he created large branches in length but semi thick. He continued to extend his arms 4 more times and constructed himself a living tree bridge to cross the river. As he crossed, he found an odd group of people of different color, shapes, and height. One of them had fur, to which he stared at. With the curiosity to explore new areas, he followed them onto their ship. To which he was introduced to Star Lord and the rest of his gang. This is my intake on how groot was formed.

**Comment by Ianjon** [comment]
Genre is Scifi

**Comment by vlraymond** [comment]
Created "storywithinastory.txt" and pull request for large text from Ianjon
